import { Effect } from "effect"
import type { DatabaseMigration } from "../migration"

export default {
  id: "20260726182810_retire-self-improvement",
  up(tx) {
    return Effect.gen(function* () {
      // These tables reference each other, so a parent drop would fail the immediate foreign-key
      // check while its children still hold rows. Deferral lasts only for this transaction, by
      // which point every table in the graph is gone.
      yield* tx.run(`PRAGMA defer_foreign_keys = ON;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_approval_request_location_version_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_approval_request_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_approval_location_version_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_rollback_canary_run_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_rollback_location_artifact_timestamp_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_location_kind_name_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_location_status_kind_name_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_version_artifact_number_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_version_digest_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_audit_entry_location_timestamp_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_audit_entry_location_event_type_timestamp_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_audit_entry_location_expiry_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_context_desired_state_location_artifact_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_context_outbox_pending_retry_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_context_outbox_pending_slot_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_context_selection_evidence_location_created_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_baseline_tuple_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_decision_expiry_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_finding_order_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_finding_expiry_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_run_location_state_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_sample_identity_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_sample_task_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_sample_expiry_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_evaluation_suite_revision_tuple_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_generation_lease_location_pattern_attempt_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_generation_lease_pending_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_generation_lease_location_pattern_acquired_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_idempotency_identity_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_idempotency_location_expires_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_observation_location_identity_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_observation_location_pattern_occurred_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_bandit_state_key_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_generation_strategy_arm_location_strategy_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_model_route_arm_location_route_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_pull_event_location_bucket_timestamp_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_reward_event_pull_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_reward_event_location_timestamp_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_routing_decision_location_timestamp_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_slot_version_id_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_artifact_slot_location_artifact_slot_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_session_evidence_location_task_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_session_evidence_location_workload_terminal_idx\`;`)
      yield* tx.run(`DROP INDEX IF EXISTS \`self_improvement_stage_transition_version_timestamp_id_idx\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_approval_request\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_approval\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_rollback\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_artifact\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_artifact_version\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_audit_entry\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_context_desired_state\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_context_outbox\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_context_selection_evidence\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_baseline\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_decision\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_finding\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_run\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_sample\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_evaluation_suite_revision\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_generation_lease\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_idempotency\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_observation\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_bandit_state\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_generation_strategy_arm\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_model_route_arm\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_pull_event\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_reward_event\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_routing_decision\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_artifact_slot\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_session_evidence\`;`)
      yield* tx.run(`DROP TABLE \`self_improvement_stage_transition\`;`)
    })
  },
} satisfies DatabaseMigration.Migration
