import type { ResolvedThemeView } from "./v2"
import type { Theme } from "./current"

export function toCurrentTheme(view: ResolvedThemeView, mode: "dark" | "light"): Theme {
  const anchor = mode === "light" ? 800 : 200
  const secondary = (view.categorical[0] ?? view.hue.accent)[anchor]

  return {
    primary: view.text.action.primary.selected,
    secondary,
    accent: view.hue.accent[anchor],
    error: view.text.feedback.error.default,
    warning: view.text.feedback.warning.default,
    success: view.text.feedback.success.default,
    info: view.text.feedback.info.default,
    text: view.text.default,
    textMuted: view.text.subdued,
    selectedListItemText: view.text.action.primary.focused,
    background: view.background.default,
    backgroundPanel: view.background.surface.offset,
    backgroundElement: view.background.surface.overlay,
    backgroundMenu: view.background.surface.overlay,
    border: view.border.default,
    borderActive: view.scrollbar.default,
    borderSubtle: view.hue.neutral[500],
    diffAdded: view.diff.text.added,
    diffRemoved: view.diff.text.removed,
    diffContext: view.diff.text.context,
    diffHunkHeader: view.diff.text.hunkHeader,
    diffHighlightAdded: view.diff.highlight.added,
    diffHighlightRemoved: view.diff.highlight.removed,
    diffAddedBg: view.diff.background.added,
    diffRemovedBg: view.diff.background.removed,
    diffContextBg: view.diff.background.context,
    diffLineNumber: view.diff.lineNumber.text,
    diffAddedLineNumberBg: view.diff.lineNumber.background.added,
    diffRemovedLineNumberBg: view.diff.lineNumber.background.removed,
    markdownText: view.markdown.text,
    markdownHeading: view.markdown.heading,
    markdownLink: view.markdown.link,
    markdownLinkText: view.markdown.linkText,
    markdownCode: view.markdown.code,
    markdownBlockQuote: view.markdown.blockQuote,
    markdownEmph: view.markdown.emphasis,
    markdownStrong: view.markdown.strong,
    markdownHorizontalRule: view.markdown.horizontalRule,
    markdownListItem: view.markdown.listItem,
    markdownListEnumeration: view.markdown.listEnumeration,
    markdownImage: view.markdown.image,
    markdownImageText: view.markdown.imageText,
    markdownCodeBlock: view.markdown.codeBlock,
    syntaxComment: view.syntax.comment,
    syntaxKeyword: view.syntax.keyword,
    syntaxFunction: view.syntax.function,
    syntaxVariable: view.syntax.variable,
    syntaxString: view.syntax.string,
    syntaxNumber: view.syntax.number,
    syntaxType: view.syntax.type,
    syntaxOperator: view.syntax.operator,
    syntaxPunctuation: view.syntax.punctuation,
    thinkingOpacity: 0.6,
    _hasSelectedListItemText: true,
  }
}
