// Generated by @ycoding-ai/httpapi-codegen. Do not edit.
import type { Effect, Stream } from "effect"
import type { HttpApiClient } from "effect/unstable/httpapi"
import type { ClientApi } from "../../contract"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>
type EffectValue<A> = A extends Effect.Effect<infer Success, any, any> ? Success : never
type StreamValue<A> = A extends Stream.Stream<infer Success, any, any> ? Success : never

export type Endpoint0_0Output = EffectValue<ReturnType<RawClient["server.health"]["health.get"]>>
export type HealthGetOperation<E = never> = () => Effect.Effect<Endpoint0_0Output, E>

type Endpoint0_1Request = Parameters<RawClient["server.health"]["health.stop"]>[0]
export type Endpoint0_1Input = { readonly instanceID: Endpoint0_1Request["payload"]["instanceID"] }
export type Endpoint0_1Output = EffectValue<ReturnType<RawClient["server.health"]["health.stop"]>>
export type HealthStopOperation<E = never> = (input: Endpoint0_1Input) => Effect.Effect<Endpoint0_1Output, E>

export interface HealthApi<E = never> {
  readonly get: HealthGetOperation<E>
  readonly stop: HealthStopOperation<E>
}

export type Endpoint1_0Output = EffectValue<ReturnType<RawClient["server.server"]["server.get"]>>
export type ServerGetOperation<E = never> = () => Effect.Effect<Endpoint1_0Output, E>

export interface ServerApi<E = never> {
  readonly get: ServerGetOperation<E>
}

type Endpoint2_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
export type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
export type Endpoint2_0Output = EffectValue<ReturnType<RawClient["server.location"]["location.get"]>>
export type LocationGetOperation<E = never> = (input?: Endpoint2_0Input) => Effect.Effect<Endpoint2_0Output, E>

export interface LocationApi<E = never> {
  readonly get: LocationGetOperation<E>
}

type Endpoint3_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
export type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
export type Endpoint3_0Output = EffectValue<ReturnType<RawClient["server.agent"]["agent.list"]>>
export type AgentListOperation<E = never> = (input?: Endpoint3_0Input) => Effect.Effect<Endpoint3_0Output, E>

export interface AgentApi<E = never> {
  readonly list: AgentListOperation<E>
}

type Endpoint4_0Request = Parameters<RawClient["server.plugin"]["plugin.list"]>[0]
export type Endpoint4_0Input = { readonly location?: Endpoint4_0Request["query"]["location"] }
export type Endpoint4_0Output = EffectValue<ReturnType<RawClient["server.plugin"]["plugin.list"]>>
export type PluginListOperation<E = never> = (input?: Endpoint4_0Input) => Effect.Effect<Endpoint4_0Output, E>

export interface PluginApi<E = never> {
  readonly list: PluginListOperation<E>
}

type Endpoint5_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
export type Endpoint5_0Input = {
  readonly workspace?: Endpoint5_0Request["query"]["workspace"]
  readonly limit?: Endpoint5_0Request["query"]["limit"]
  readonly order?: Endpoint5_0Request["query"]["order"]
  readonly search?: Endpoint5_0Request["query"]["search"]
  readonly parentID?: Endpoint5_0Request["query"]["parentID"]
  readonly directory?: Endpoint5_0Request["query"]["directory"]
  readonly project?: Endpoint5_0Request["query"]["project"]
  readonly subpath?: Endpoint5_0Request["query"]["subpath"]
  readonly cursor?: Endpoint5_0Request["query"]["cursor"]
}
export type Endpoint5_0Output = EffectValue<ReturnType<RawClient["server.session"]["session.list"]>>
export type SessionListOperation<E = never> = (input?: Endpoint5_0Input) => Effect.Effect<Endpoint5_0Output, E>

type Endpoint5_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
export type Endpoint5_1Input = {
  readonly id?: Endpoint5_1Request["payload"]["id"]
  readonly parentID?: Endpoint5_1Request["payload"]["parentID"]
  readonly agent?: Endpoint5_1Request["payload"]["agent"]
  readonly model?: Endpoint5_1Request["payload"]["model"]
  readonly location?: Endpoint5_1Request["payload"]["location"]
}
export type Endpoint5_1Output = EffectValue<ReturnType<RawClient["server.session"]["session.create"]>>["data"]
export type SessionCreateOperation<E = never> = (input?: Endpoint5_1Input) => Effect.Effect<Endpoint5_1Output, E>

export type Endpoint5_2Output = EffectValue<ReturnType<RawClient["server.session"]["session.active"]>>["data"]
export type SessionActiveOperation<E = never> = () => Effect.Effect<Endpoint5_2Output, E>

type Endpoint5_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
export type Endpoint5_3Input = { readonly sessionID: Endpoint5_3Request["params"]["sessionID"] }
export type Endpoint5_3Output = EffectValue<ReturnType<RawClient["server.session"]["session.get"]>>["data"]
export type SessionGetOperation<E = never> = (input: Endpoint5_3Input) => Effect.Effect<Endpoint5_3Output, E>

type Endpoint5_4Request = Parameters<RawClient["server.session"]["session.diagnostics"]>[0]
export type Endpoint5_4Input = { readonly sessionID: Endpoint5_4Request["params"]["sessionID"] }
export type Endpoint5_4Output = EffectValue<ReturnType<RawClient["server.session"]["session.diagnostics"]>>["data"]
export type SessionDiagnosticsOperation<E = never> = (input: Endpoint5_4Input) => Effect.Effect<Endpoint5_4Output, E>

type Endpoint5_5Request = Parameters<RawClient["server.session"]["session.autonomy.get"]>[0]
export type Endpoint5_5Input = { readonly sessionID: Endpoint5_5Request["params"]["sessionID"] }
export type Endpoint5_5Output = EffectValue<ReturnType<RawClient["server.session"]["session.autonomy.get"]>>["data"]
export type SessionAutonomyGetOperation<E = never> = (input: Endpoint5_5Input) => Effect.Effect<Endpoint5_5Output, E>

type Endpoint5_6Request = Parameters<RawClient["server.session"]["session.autonomy.set"]>[0]
export type Endpoint5_6Input = {
  readonly sessionID: Endpoint5_6Request["params"]["sessionID"]
  readonly payload: Endpoint5_6Request["payload"]
}
export type Endpoint5_6Output = EffectValue<ReturnType<RawClient["server.session"]["session.autonomy.set"]>>["data"]
export type SessionAutonomySetOperation<E = never> = (input: Endpoint5_6Input) => Effect.Effect<Endpoint5_6Output, E>

type Endpoint5_7Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
export type Endpoint5_7Input = { readonly sessionID: Endpoint5_7Request["params"]["sessionID"] }
export type Endpoint5_7Output = EffectValue<ReturnType<RawClient["server.session"]["session.remove"]>>
export type SessionRemoveOperation<E = never> = (input: Endpoint5_7Input) => Effect.Effect<Endpoint5_7Output, E>

type Endpoint5_8Request = Parameters<RawClient["server.session"]["session.subagent.list"]>[0]
export type Endpoint5_8Input = { readonly parentID: Endpoint5_8Request["params"]["parentID"] }
export type Endpoint5_8Output = EffectValue<ReturnType<RawClient["server.session"]["session.subagent.list"]>>["data"]
export type SessionSubagentListOperation<E = never> = (input: Endpoint5_8Input) => Effect.Effect<Endpoint5_8Output, E>

type Endpoint5_9Request = Parameters<RawClient["server.session"]["session.subagent.launch"]>[0]
export type Endpoint5_9Input = {
  readonly parentID: Endpoint5_9Request["params"]["parentID"]
  readonly parentAssistantMessageID: Endpoint5_9Request["payload"]["parentAssistantMessageID"]
  readonly toolCallID: Endpoint5_9Request["payload"]["toolCallID"]
  readonly agent: Endpoint5_9Request["payload"]["agent"]
  readonly description: Endpoint5_9Request["payload"]["description"]
  readonly prompt: Endpoint5_9Request["payload"]["prompt"]
  readonly background?: Endpoint5_9Request["payload"]["background"]
  readonly model?: Endpoint5_9Request["payload"]["model"]
}
export type Endpoint5_9Output = EffectValue<ReturnType<RawClient["server.session"]["session.subagent.launch"]>>["data"]
export type SessionSubagentLaunchOperation<E = never> = (input: Endpoint5_9Input) => Effect.Effect<Endpoint5_9Output, E>

type Endpoint5_10Request = Parameters<RawClient["server.session"]["session.subagent.message"]>[0]
export type Endpoint5_10Input = {
  readonly parentID: Endpoint5_10Request["params"]["parentID"]
  readonly childID: Endpoint5_10Request["params"]["childID"]
  readonly messageID: Endpoint5_10Request["payload"]["messageID"]
  readonly text: Endpoint5_10Request["payload"]["text"]
  readonly delivery: Endpoint5_10Request["payload"]["delivery"]
}
export type Endpoint5_10Output = EffectValue<
  ReturnType<RawClient["server.session"]["session.subagent.message"]>
>["data"]
export type SessionSubagentMessageOperation<E = never> = (
  input: Endpoint5_10Input,
) => Effect.Effect<Endpoint5_10Output, E>

type Endpoint5_11Request = Parameters<RawClient["server.session"]["session.subagent.answer"]>[0]
export type Endpoint5_11Input = {
  readonly parentID: Endpoint5_11Request["params"]["parentID"]
  readonly childID: Endpoint5_11Request["params"]["childID"]
  readonly questionID: Endpoint5_11Request["params"]["questionID"]
  readonly text?: Endpoint5_11Request["payload"]["text"]
  readonly data?: Endpoint5_11Request["payload"]["data"]
}
export type Endpoint5_11Output = EffectValue<ReturnType<RawClient["server.session"]["session.subagent.answer"]>>["data"]
export type SessionSubagentAnswerOperation<E = never> = (
  input: Endpoint5_11Input,
) => Effect.Effect<Endpoint5_11Output, E>

type Endpoint5_12Request = Parameters<RawClient["server.session"]["session.subagent.cancel"]>[0]
export type Endpoint5_12Input = {
  readonly parentID: Endpoint5_12Request["params"]["parentID"]
  readonly childID: Endpoint5_12Request["params"]["childID"]
}
export type Endpoint5_12Output = EffectValue<ReturnType<RawClient["server.session"]["session.subagent.cancel"]>>["data"]
export type SessionSubagentCancelOperation<E = never> = (
  input: Endpoint5_12Input,
) => Effect.Effect<Endpoint5_12Output, E>

type Endpoint5_13Request = Parameters<RawClient["server.session"]["session.subagent.resume"]>[0]
export type Endpoint5_13Input = {
  readonly parentID: Endpoint5_13Request["params"]["parentID"]
  readonly childID: Endpoint5_13Request["params"]["childID"]
}
export type Endpoint5_13Output = EffectValue<ReturnType<RawClient["server.session"]["session.subagent.resume"]>>["data"]
export type SessionSubagentResumeOperation<E = never> = (
  input: Endpoint5_13Input,
) => Effect.Effect<Endpoint5_13Output, E>

type Endpoint5_14Request = Parameters<RawClient["server.session"]["session.todo.list"]>[0]
export type Endpoint5_14Input = { readonly sessionID: Endpoint5_14Request["params"]["sessionID"] }
export type Endpoint5_14Output = EffectValue<ReturnType<RawClient["server.session"]["session.todo.list"]>>["data"]
export type SessionTodoListOperation<E = never> = (input: Endpoint5_14Input) => Effect.Effect<Endpoint5_14Output, E>

type Endpoint5_15Request = Parameters<RawClient["server.session"]["session.todo.update"]>[0]
export type Endpoint5_15Input = {
  readonly sessionID: Endpoint5_15Request["params"]["sessionID"]
  readonly todos: Endpoint5_15Request["payload"]["todos"]
}
export type Endpoint5_15Output = EffectValue<ReturnType<RawClient["server.session"]["session.todo.update"]>>["data"]
export type SessionTodoUpdateOperation<E = never> = (input: Endpoint5_15Input) => Effect.Effect<Endpoint5_15Output, E>

type Endpoint5_16Request = Parameters<RawClient["server.session"]["session.fork"]>[0]
export type Endpoint5_16Input = {
  readonly sessionID: Endpoint5_16Request["params"]["sessionID"]
  readonly messageID?: Endpoint5_16Request["payload"]["messageID"]
}
export type Endpoint5_16Output = EffectValue<ReturnType<RawClient["server.session"]["session.fork"]>>["data"]
export type SessionForkOperation<E = never> = (input: Endpoint5_16Input) => Effect.Effect<Endpoint5_16Output, E>

type Endpoint5_17Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
export type Endpoint5_17Input = {
  readonly sessionID: Endpoint5_17Request["params"]["sessionID"]
  readonly agent: Endpoint5_17Request["payload"]["agent"]
}
export type Endpoint5_17Output = EffectValue<ReturnType<RawClient["server.session"]["session.switchAgent"]>>
export type SessionSwitchAgentOperation<E = never> = (input: Endpoint5_17Input) => Effect.Effect<Endpoint5_17Output, E>

type Endpoint5_18Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
export type Endpoint5_18Input = {
  readonly sessionID: Endpoint5_18Request["params"]["sessionID"]
  readonly model: Endpoint5_18Request["payload"]["model"]
}
export type Endpoint5_18Output = EffectValue<ReturnType<RawClient["server.session"]["session.switchModel"]>>
export type SessionSwitchModelOperation<E = never> = (input: Endpoint5_18Input) => Effect.Effect<Endpoint5_18Output, E>

type Endpoint5_19Request = Parameters<RawClient["server.session"]["session.rename"]>[0]
export type Endpoint5_19Input = {
  readonly sessionID: Endpoint5_19Request["params"]["sessionID"]
  readonly title: Endpoint5_19Request["payload"]["title"]
}
export type Endpoint5_19Output = EffectValue<ReturnType<RawClient["server.session"]["session.rename"]>>
export type SessionRenameOperation<E = never> = (input: Endpoint5_19Input) => Effect.Effect<Endpoint5_19Output, E>

type Endpoint5_20Request = Parameters<RawClient["server.session"]["session.move"]>[0]
export type Endpoint5_20Input = {
  readonly sessionID: Endpoint5_20Request["params"]["sessionID"]
  readonly directory: Endpoint5_20Request["payload"]["directory"]
  readonly workspaceID?: Endpoint5_20Request["payload"]["workspaceID"]
}
export type Endpoint5_20Output = EffectValue<ReturnType<RawClient["server.session"]["session.move"]>>
export type SessionMoveOperation<E = never> = (input: Endpoint5_20Input) => Effect.Effect<Endpoint5_20Output, E>

type Endpoint5_21Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
export type Endpoint5_21Input = {
  readonly sessionID: Endpoint5_21Request["params"]["sessionID"]
  readonly id?: Endpoint5_21Request["payload"]["id"]
  readonly text: Endpoint5_21Request["payload"]["text"]
  readonly files?: Endpoint5_21Request["payload"]["files"]
  readonly agents?: Endpoint5_21Request["payload"]["agents"]
  readonly metadata?: Endpoint5_21Request["payload"]["metadata"]
  readonly delivery?: Endpoint5_21Request["payload"]["delivery"]
  readonly resume?: Endpoint5_21Request["payload"]["resume"]
}
export type Endpoint5_21Output = EffectValue<ReturnType<RawClient["server.session"]["session.prompt"]>>["data"]
export type SessionPromptOperation<E = never> = (input: Endpoint5_21Input) => Effect.Effect<Endpoint5_21Output, E>

type Endpoint5_22Request = Parameters<RawClient["server.session"]["session.command"]>[0]
export type Endpoint5_22Input = {
  readonly sessionID: Endpoint5_22Request["params"]["sessionID"]
  readonly id?: Endpoint5_22Request["payload"]["id"]
  readonly command: Endpoint5_22Request["payload"]["command"]
  readonly arguments?: Endpoint5_22Request["payload"]["arguments"]
  readonly agent?: Endpoint5_22Request["payload"]["agent"]
  readonly model?: Endpoint5_22Request["payload"]["model"]
  readonly files?: Endpoint5_22Request["payload"]["files"]
  readonly agents?: Endpoint5_22Request["payload"]["agents"]
  readonly delivery?: Endpoint5_22Request["payload"]["delivery"]
  readonly resume?: Endpoint5_22Request["payload"]["resume"]
}
export type Endpoint5_22Output = EffectValue<ReturnType<RawClient["server.session"]["session.command"]>>["data"]
export type SessionCommandOperation<E = never> = (input: Endpoint5_22Input) => Effect.Effect<Endpoint5_22Output, E>

type Endpoint5_23Request = Parameters<RawClient["server.session"]["session.skill"]>[0]
export type Endpoint5_23Input = {
  readonly sessionID: Endpoint5_23Request["params"]["sessionID"]
  readonly id?: Endpoint5_23Request["payload"]["id"]
  readonly skill: Endpoint5_23Request["payload"]["skill"]
  readonly resume?: Endpoint5_23Request["payload"]["resume"]
}
export type Endpoint5_23Output = EffectValue<ReturnType<RawClient["server.session"]["session.skill"]>>
export type SessionSkillOperation<E = never> = (input: Endpoint5_23Input) => Effect.Effect<Endpoint5_23Output, E>

type Endpoint5_24Request = Parameters<RawClient["server.session"]["session.skills"]>[0]
export type Endpoint5_24Input = { readonly sessionID: Endpoint5_24Request["params"]["sessionID"] }
export type Endpoint5_24Output = EffectValue<ReturnType<RawClient["server.session"]["session.skills"]>>["data"]
export type SessionSkillsOperation<E = never> = (input: Endpoint5_24Input) => Effect.Effect<Endpoint5_24Output, E>

type Endpoint5_25Request = Parameters<RawClient["server.session"]["session.synthetic"]>[0]
export type Endpoint5_25Input = {
  readonly sessionID: Endpoint5_25Request["params"]["sessionID"]
  readonly id?: Endpoint5_25Request["payload"]["id"]
  readonly text: Endpoint5_25Request["payload"]["text"]
  readonly description?: Endpoint5_25Request["payload"]["description"]
  readonly metadata?: Endpoint5_25Request["payload"]["metadata"]
  readonly delivery?: Endpoint5_25Request["payload"]["delivery"]
  readonly resume?: Endpoint5_25Request["payload"]["resume"]
}
export type Endpoint5_25Output = EffectValue<ReturnType<RawClient["server.session"]["session.synthetic"]>>["data"]
export type SessionSyntheticOperation<E = never> = (input: Endpoint5_25Input) => Effect.Effect<Endpoint5_25Output, E>

type Endpoint5_26Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
export type Endpoint5_26Input = {
  readonly sessionID: Endpoint5_26Request["params"]["sessionID"]
  readonly id?: Endpoint5_26Request["payload"]["id"]
  readonly command: Endpoint5_26Request["payload"]["command"]
}
export type Endpoint5_26Output = EffectValue<ReturnType<RawClient["server.session"]["session.shell"]>>
export type SessionShellOperation<E = never> = (input: Endpoint5_26Input) => Effect.Effect<Endpoint5_26Output, E>

type Endpoint5_27Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
export type Endpoint5_27Input = {
  readonly sessionID: Endpoint5_27Request["params"]["sessionID"]
  readonly id?: Endpoint5_27Request["payload"]["id"]
}
export type Endpoint5_27Output = EffectValue<ReturnType<RawClient["server.session"]["session.compact"]>>["data"]
export type SessionCompactOperation<E = never> = (input: Endpoint5_27Input) => Effect.Effect<Endpoint5_27Output, E>

type Endpoint5_28Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
export type Endpoint5_28Input = { readonly sessionID: Endpoint5_28Request["params"]["sessionID"] }
export type Endpoint5_28Output = EffectValue<ReturnType<RawClient["server.session"]["session.wait"]>>
export type SessionWaitOperation<E = never> = (input: Endpoint5_28Input) => Effect.Effect<Endpoint5_28Output, E>

type Endpoint5_29Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
export type Endpoint5_29Input = {
  readonly sessionID: Endpoint5_29Request["params"]["sessionID"]
  readonly messageID: Endpoint5_29Request["payload"]["messageID"]
  readonly files?: Endpoint5_29Request["payload"]["files"]
}
export type Endpoint5_29Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.stage"]>>["data"]
export type SessionRevertStageOperation<E = never> = (input: Endpoint5_29Input) => Effect.Effect<Endpoint5_29Output, E>

type Endpoint5_30Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
export type Endpoint5_30Input = { readonly sessionID: Endpoint5_30Request["params"]["sessionID"] }
export type Endpoint5_30Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.clear"]>>
export type SessionRevertClearOperation<E = never> = (input: Endpoint5_30Input) => Effect.Effect<Endpoint5_30Output, E>

type Endpoint5_31Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
export type Endpoint5_31Input = { readonly sessionID: Endpoint5_31Request["params"]["sessionID"] }
export type Endpoint5_31Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.commit"]>>
export type SessionRevertCommitOperation<E = never> = (input: Endpoint5_31Input) => Effect.Effect<Endpoint5_31Output, E>

type Endpoint5_32Request = Parameters<RawClient["server.session"]["session.context"]>[0]
export type Endpoint5_32Input = { readonly sessionID: Endpoint5_32Request["params"]["sessionID"] }
export type Endpoint5_32Output = EffectValue<ReturnType<RawClient["server.session"]["session.context"]>>["data"]
export type SessionContextOperation<E = never> = (input: Endpoint5_32Input) => Effect.Effect<Endpoint5_32Output, E>

type Endpoint5_33Request = Parameters<RawClient["server.session"]["session.pending.list"]>[0]
export type Endpoint5_33Input = { readonly sessionID: Endpoint5_33Request["params"]["sessionID"] }
export type Endpoint5_33Output = EffectValue<ReturnType<RawClient["server.session"]["session.pending.list"]>>["data"]
export type SessionPendingListOperation<E = never> = (input: Endpoint5_33Input) => Effect.Effect<Endpoint5_33Output, E>

type Endpoint5_34Request = Parameters<RawClient["server.session"]["session.instructions.entry.list"]>[0]
export type Endpoint5_34Input = { readonly sessionID: Endpoint5_34Request["params"]["sessionID"] }
export type Endpoint5_34Output = EffectValue<
  ReturnType<RawClient["server.session"]["session.instructions.entry.list"]>
>["data"]
export type SessionInstructionsEntryListOperation<E = never> = (
  input: Endpoint5_34Input,
) => Effect.Effect<Endpoint5_34Output, E>

type Endpoint5_35Request = Parameters<RawClient["server.session"]["session.instructions.entry.put"]>[0]
export type Endpoint5_35Input = {
  readonly sessionID: Endpoint5_35Request["params"]["sessionID"]
  readonly key: Endpoint5_35Request["params"]["key"]
  readonly value: Endpoint5_35Request["payload"]["value"]
}
export type Endpoint5_35Output = EffectValue<ReturnType<RawClient["server.session"]["session.instructions.entry.put"]>>
export type SessionInstructionsEntryPutOperation<E = never> = (
  input: Endpoint5_35Input,
) => Effect.Effect<Endpoint5_35Output, E>

type Endpoint5_36Request = Parameters<RawClient["server.session"]["session.instructions.entry.remove"]>[0]
export type Endpoint5_36Input = {
  readonly sessionID: Endpoint5_36Request["params"]["sessionID"]
  readonly key: Endpoint5_36Request["params"]["key"]
}
export type Endpoint5_36Output = EffectValue<
  ReturnType<RawClient["server.session"]["session.instructions.entry.remove"]>
>
export type SessionInstructionsEntryRemoveOperation<E = never> = (
  input: Endpoint5_36Input,
) => Effect.Effect<Endpoint5_36Output, E>

type Endpoint5_37Request = Parameters<RawClient["server.session"]["session.generate"]>[0]
export type Endpoint5_37Input = {
  readonly sessionID: Endpoint5_37Request["params"]["sessionID"]
  readonly prompt: Endpoint5_37Request["payload"]["prompt"]
}
export type Endpoint5_37Output = EffectValue<ReturnType<RawClient["server.session"]["session.generate"]>>["data"]
export type SessionGenerateOperation<E = never> = (input: Endpoint5_37Input) => Effect.Effect<Endpoint5_37Output, E>

type Endpoint5_38Request = Parameters<RawClient["server.session"]["session.log"]>[0]
export type Endpoint5_38Input = {
  readonly sessionID: Endpoint5_38Request["params"]["sessionID"]
  readonly after?: Endpoint5_38Request["query"]["after"]
  readonly follow?: Endpoint5_38Request["query"]["follow"]
}
export type Endpoint5_38Output = StreamValue<EffectValue<ReturnType<RawClient["server.session"]["session.log"]>>>
export type SessionLogOperation<E = never> = (input: Endpoint5_38Input) => Stream.Stream<Endpoint5_38Output, E>

type Endpoint5_39Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
export type Endpoint5_39Input = { readonly sessionID: Endpoint5_39Request["params"]["sessionID"] }
export type Endpoint5_39Output = EffectValue<ReturnType<RawClient["server.session"]["session.interrupt"]>>
export type SessionInterruptOperation<E = never> = (input: Endpoint5_39Input) => Effect.Effect<Endpoint5_39Output, E>

type Endpoint5_40Request = Parameters<RawClient["server.session"]["session.background"]>[0]
export type Endpoint5_40Input = { readonly sessionID: Endpoint5_40Request["params"]["sessionID"] }
export type Endpoint5_40Output = EffectValue<ReturnType<RawClient["server.session"]["session.background"]>>
export type SessionBackgroundOperation<E = never> = (input: Endpoint5_40Input) => Effect.Effect<Endpoint5_40Output, E>

type Endpoint5_41Request = Parameters<RawClient["server.session"]["session.message"]>[0]
export type Endpoint5_41Input = {
  readonly sessionID: Endpoint5_41Request["params"]["sessionID"]
  readonly messageID: Endpoint5_41Request["params"]["messageID"]
}
export type Endpoint5_41Output = EffectValue<ReturnType<RawClient["server.session"]["session.message"]>>["data"]
export type SessionMessageOperation<E = never> = (input: Endpoint5_41Input) => Effect.Effect<Endpoint5_41Output, E>

export interface SessionApi<E = never> {
  readonly list: SessionListOperation<E>
  readonly create: SessionCreateOperation<E>
  readonly active: SessionActiveOperation<E>
  readonly get: SessionGetOperation<E>
  readonly diagnostics: SessionDiagnosticsOperation<E>
  readonly autonomy: { readonly get: SessionAutonomyGetOperation<E>; readonly set: SessionAutonomySetOperation<E> }
  readonly remove: SessionRemoveOperation<E>
  readonly subagent: {
    readonly list: SessionSubagentListOperation<E>
    readonly launch: SessionSubagentLaunchOperation<E>
    readonly message: SessionSubagentMessageOperation<E>
    readonly answer: SessionSubagentAnswerOperation<E>
    readonly cancel: SessionSubagentCancelOperation<E>
    readonly resume: SessionSubagentResumeOperation<E>
  }
  readonly todo: { readonly list: SessionTodoListOperation<E>; readonly update: SessionTodoUpdateOperation<E> }
  readonly fork: SessionForkOperation<E>
  readonly switchAgent: SessionSwitchAgentOperation<E>
  readonly switchModel: SessionSwitchModelOperation<E>
  readonly rename: SessionRenameOperation<E>
  readonly move: SessionMoveOperation<E>
  readonly prompt: SessionPromptOperation<E>
  readonly command: SessionCommandOperation<E>
  readonly skill: SessionSkillOperation<E>
  readonly skills: SessionSkillsOperation<E>
  readonly synthetic: SessionSyntheticOperation<E>
  readonly shell: SessionShellOperation<E>
  readonly compact: SessionCompactOperation<E>
  readonly wait: SessionWaitOperation<E>
  readonly revert: {
    readonly stage: SessionRevertStageOperation<E>
    readonly clear: SessionRevertClearOperation<E>
    readonly commit: SessionRevertCommitOperation<E>
  }
  readonly context: SessionContextOperation<E>
  readonly pending: { readonly list: SessionPendingListOperation<E> }
  readonly instructions: {
    readonly entry: {
      readonly list: SessionInstructionsEntryListOperation<E>
      readonly put: SessionInstructionsEntryPutOperation<E>
      readonly remove: SessionInstructionsEntryRemoveOperation<E>
    }
  }
  readonly generate: SessionGenerateOperation<E>
  readonly log: SessionLogOperation<E>
  readonly interrupt: SessionInterruptOperation<E>
  readonly background: SessionBackgroundOperation<E>
  readonly message: SessionMessageOperation<E>
}

type Endpoint6_0Request = Parameters<RawClient["server.guardrail"]["session.guardrail.status"]>[0]
export type Endpoint6_0Input = { readonly sessionID: Endpoint6_0Request["params"]["sessionID"] }
export type Endpoint6_0Output = EffectValue<
  ReturnType<RawClient["server.guardrail"]["session.guardrail.status"]>
>["data"]
export type GuardrailStatusOperation<E = never> = (input: Endpoint6_0Input) => Effect.Effect<Endpoint6_0Output, E>

type Endpoint6_1Request = Parameters<RawClient["server.guardrail"]["session.guardrail.request.list"]>[0]
export type Endpoint6_1Input = { readonly sessionID: Endpoint6_1Request["params"]["sessionID"] }
export type Endpoint6_1Output = EffectValue<
  ReturnType<RawClient["server.guardrail"]["session.guardrail.request.list"]>
>["data"]
export type GuardrailRequestListOperation<E = never> = (input: Endpoint6_1Input) => Effect.Effect<Endpoint6_1Output, E>

type Endpoint6_2Request = Parameters<RawClient["server.guardrail"]["session.guardrail.request.reply"]>[0]
export type Endpoint6_2Input = {
  readonly sessionID: Endpoint6_2Request["params"]["sessionID"]
  readonly requestID: Endpoint6_2Request["params"]["requestID"]
  readonly reply: Endpoint6_2Request["payload"]["reply"]
}
export type Endpoint6_2Output = EffectValue<
  ReturnType<RawClient["server.guardrail"]["session.guardrail.request.reply"]>
>
export type GuardrailRequestReplyOperation<E = never> = (input: Endpoint6_2Input) => Effect.Effect<Endpoint6_2Output, E>

export interface GuardrailApi<E = never> {
  readonly status: GuardrailStatusOperation<E>
  readonly request: {
    readonly list: GuardrailRequestListOperation<E>
    readonly reply: GuardrailRequestReplyOperation<E>
  }
}

type Endpoint7_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
export type Endpoint7_0Input = {
  readonly sessionID: Endpoint7_0Request["params"]["sessionID"]
  readonly limit?: Endpoint7_0Request["query"]["limit"]
  readonly order?: Endpoint7_0Request["query"]["order"]
  readonly cursor?: Endpoint7_0Request["query"]["cursor"]
}
export type Endpoint7_0Output = EffectValue<ReturnType<RawClient["server.message"]["session.messages"]>>
export type MessageListOperation<E = never> = (input: Endpoint7_0Input) => Effect.Effect<Endpoint7_0Output, E>

export interface MessageApi<E = never> {
  readonly list: MessageListOperation<E>
}

type Endpoint8_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
export type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
export type Endpoint8_0Output = EffectValue<ReturnType<RawClient["server.model"]["model.list"]>>
export type ModelListOperation<E = never> = (input?: Endpoint8_0Input) => Effect.Effect<Endpoint8_0Output, E>

type Endpoint8_1Request = Parameters<RawClient["server.model"]["model.default"]>[0]
export type Endpoint8_1Input = { readonly location?: Endpoint8_1Request["query"]["location"] }
export type Endpoint8_1Output = EffectValue<ReturnType<RawClient["server.model"]["model.default"]>>
export type ModelDefaultOperation<E = never> = (input?: Endpoint8_1Input) => Effect.Effect<Endpoint8_1Output, E>

export interface ModelApi<E = never> {
  readonly list: ModelListOperation<E>
  readonly default: ModelDefaultOperation<E>
}

type Endpoint9_0Request = Parameters<RawClient["server.generate"]["generate.text"]>[0]
export type Endpoint9_0Input = {
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly prompt: Endpoint9_0Request["payload"]["prompt"]
  readonly model?: Endpoint9_0Request["payload"]["model"]
}
export type Endpoint9_0Output = EffectValue<ReturnType<RawClient["server.generate"]["generate.text"]>>["data"]
export type GenerateTextOperation<E = never> = (input: Endpoint9_0Input) => Effect.Effect<Endpoint9_0Output, E>

export interface GenerateApi<E = never> {
  readonly text: GenerateTextOperation<E>
}

type Endpoint10_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
export type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
export type Endpoint10_0Output = EffectValue<ReturnType<RawClient["server.provider"]["provider.list"]>>
export type ProviderListOperation<E = never> = (input?: Endpoint10_0Input) => Effect.Effect<Endpoint10_0Output, E>

type Endpoint10_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
export type Endpoint10_1Input = {
  readonly providerID: Endpoint10_1Request["params"]["providerID"]
  readonly location?: Endpoint10_1Request["query"]["location"]
}
export type Endpoint10_1Output = EffectValue<ReturnType<RawClient["server.provider"]["provider.get"]>>
export type ProviderGetOperation<E = never> = (input: Endpoint10_1Input) => Effect.Effect<Endpoint10_1Output, E>

export interface ProviderApi<E = never> {
  readonly list: ProviderListOperation<E>
  readonly get: ProviderGetOperation<E>
}

type Endpoint11_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
export type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
export type Endpoint11_0Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.list"]>>
export type IntegrationListOperation<E = never> = (input?: Endpoint11_0Input) => Effect.Effect<Endpoint11_0Output, E>

type Endpoint11_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
export type Endpoint11_1Input = {
  readonly integrationID: Endpoint11_1Request["params"]["integrationID"]
  readonly location?: Endpoint11_1Request["query"]["location"]
}
export type Endpoint11_1Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.get"]>>
export type IntegrationGetOperation<E = never> = (input: Endpoint11_1Input) => Effect.Effect<Endpoint11_1Output, E>

type Endpoint11_2Request = Parameters<RawClient["server.integration"]["integration.wellknown.add"]>[0]
export type Endpoint11_2Input = {
  readonly location?: Endpoint11_2Request["query"]["location"]
  readonly url: Endpoint11_2Request["payload"]["url"]
}
export type Endpoint11_2Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.wellknown.add"]>>
export type IntegrationWellknownAddOperation<E = never> = (
  input: Endpoint11_2Input,
) => Effect.Effect<Endpoint11_2Output, E>

type Endpoint11_3Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
export type Endpoint11_3Input = {
  readonly integrationID: Endpoint11_3Request["params"]["integrationID"]
  readonly location?: Endpoint11_3Request["query"]["location"]
  readonly key: Endpoint11_3Request["payload"]["key"]
  readonly label?: Endpoint11_3Request["payload"]["label"]
}
export type Endpoint11_3Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.connect.key"]>>
export type IntegrationConnectKeyOperation<E = never> = (
  input: Endpoint11_3Input,
) => Effect.Effect<Endpoint11_3Output, E>

type Endpoint11_4Request = Parameters<RawClient["server.integration"]["integration.oauth.connect"]>[0]
export type Endpoint11_4Input = {
  readonly integrationID: Endpoint11_4Request["params"]["integrationID"]
  readonly location?: Endpoint11_4Request["query"]["location"]
  readonly methodID: Endpoint11_4Request["payload"]["methodID"]
  readonly inputs: Endpoint11_4Request["payload"]["inputs"]
  readonly label?: Endpoint11_4Request["payload"]["label"]
}
export type Endpoint11_4Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.oauth.connect"]>>
export type IntegrationOauthConnectOperation<E = never> = (
  input: Endpoint11_4Input,
) => Effect.Effect<Endpoint11_4Output, E>

type Endpoint11_5Request = Parameters<RawClient["server.integration"]["integration.oauth.status"]>[0]
export type Endpoint11_5Input = {
  readonly integrationID: Endpoint11_5Request["params"]["integrationID"]
  readonly attemptID: Endpoint11_5Request["params"]["attemptID"]
  readonly location?: Endpoint11_5Request["query"]["location"]
}
export type Endpoint11_5Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.oauth.status"]>>
export type IntegrationOauthStatusOperation<E = never> = (
  input: Endpoint11_5Input,
) => Effect.Effect<Endpoint11_5Output, E>

type Endpoint11_6Request = Parameters<RawClient["server.integration"]["integration.oauth.complete"]>[0]
export type Endpoint11_6Input = {
  readonly integrationID: Endpoint11_6Request["params"]["integrationID"]
  readonly attemptID: Endpoint11_6Request["params"]["attemptID"]
  readonly location?: Endpoint11_6Request["query"]["location"]
  readonly code?: Endpoint11_6Request["payload"]["code"]
}
export type Endpoint11_6Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.oauth.complete"]>>
export type IntegrationOauthCompleteOperation<E = never> = (
  input: Endpoint11_6Input,
) => Effect.Effect<Endpoint11_6Output, E>

type Endpoint11_7Request = Parameters<RawClient["server.integration"]["integration.oauth.cancel"]>[0]
export type Endpoint11_7Input = {
  readonly integrationID: Endpoint11_7Request["params"]["integrationID"]
  readonly attemptID: Endpoint11_7Request["params"]["attemptID"]
  readonly location?: Endpoint11_7Request["query"]["location"]
}
export type Endpoint11_7Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.oauth.cancel"]>>
export type IntegrationOauthCancelOperation<E = never> = (
  input: Endpoint11_7Input,
) => Effect.Effect<Endpoint11_7Output, E>

type Endpoint11_8Request = Parameters<RawClient["server.integration"]["integration.command.connect"]>[0]
export type Endpoint11_8Input = {
  readonly integrationID: Endpoint11_8Request["params"]["integrationID"]
  readonly location?: Endpoint11_8Request["query"]["location"]
  readonly methodID: Endpoint11_8Request["payload"]["methodID"]
  readonly label?: Endpoint11_8Request["payload"]["label"]
}
export type Endpoint11_8Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.command.connect"]>>
export type IntegrationCommandConnectOperation<E = never> = (
  input: Endpoint11_8Input,
) => Effect.Effect<Endpoint11_8Output, E>

type Endpoint11_9Request = Parameters<RawClient["server.integration"]["integration.command.status"]>[0]
export type Endpoint11_9Input = {
  readonly integrationID: Endpoint11_9Request["params"]["integrationID"]
  readonly attemptID: Endpoint11_9Request["params"]["attemptID"]
  readonly location?: Endpoint11_9Request["query"]["location"]
}
export type Endpoint11_9Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.command.status"]>>
export type IntegrationCommandStatusOperation<E = never> = (
  input: Endpoint11_9Input,
) => Effect.Effect<Endpoint11_9Output, E>

type Endpoint11_10Request = Parameters<RawClient["server.integration"]["integration.command.cancel"]>[0]
export type Endpoint11_10Input = {
  readonly integrationID: Endpoint11_10Request["params"]["integrationID"]
  readonly attemptID: Endpoint11_10Request["params"]["attemptID"]
  readonly location?: Endpoint11_10Request["query"]["location"]
}
export type Endpoint11_10Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.command.cancel"]>>
export type IntegrationCommandCancelOperation<E = never> = (
  input: Endpoint11_10Input,
) => Effect.Effect<Endpoint11_10Output, E>

export interface IntegrationApi<E = never> {
  readonly list: IntegrationListOperation<E>
  readonly get: IntegrationGetOperation<E>
  readonly wellknown: { readonly add: IntegrationWellknownAddOperation<E> }
  readonly connect: { readonly key: IntegrationConnectKeyOperation<E> }
  readonly oauth: {
    readonly connect: IntegrationOauthConnectOperation<E>
    readonly status: IntegrationOauthStatusOperation<E>
    readonly complete: IntegrationOauthCompleteOperation<E>
    readonly cancel: IntegrationOauthCancelOperation<E>
  }
  readonly command: {
    readonly connect: IntegrationCommandConnectOperation<E>
    readonly status: IntegrationCommandStatusOperation<E>
    readonly cancel: IntegrationCommandCancelOperation<E>
  }
}

type Endpoint12_0Request = Parameters<RawClient["server.mcp"]["mcp.list"]>[0]
export type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
export type Endpoint12_0Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.list"]>>
export type McpListOperation<E = never> = (input?: Endpoint12_0Input) => Effect.Effect<Endpoint12_0Output, E>

type Endpoint12_1Request = Parameters<RawClient["server.mcp"]["mcp.add"]>[0]
export type Endpoint12_1Input = {
  readonly server: Endpoint12_1Request["params"]["server"]
  readonly location?: Endpoint12_1Request["query"]["location"]
  readonly config: Endpoint12_1Request["payload"]["config"]
}
export type Endpoint12_1Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.add"]>>
export type McpAddOperation<E = never> = (input: Endpoint12_1Input) => Effect.Effect<Endpoint12_1Output, E>

type Endpoint12_2Request = Parameters<RawClient["server.mcp"]["mcp.remove"]>[0]
export type Endpoint12_2Input = {
  readonly server: Endpoint12_2Request["params"]["server"]
  readonly location?: Endpoint12_2Request["query"]["location"]
}
export type Endpoint12_2Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.remove"]>>
export type McpRemoveOperation<E = never> = (input: Endpoint12_2Input) => Effect.Effect<Endpoint12_2Output, E>

type Endpoint12_3Request = Parameters<RawClient["server.mcp"]["mcp.connect"]>[0]
export type Endpoint12_3Input = {
  readonly server: Endpoint12_3Request["params"]["server"]
  readonly location?: Endpoint12_3Request["query"]["location"]
}
export type Endpoint12_3Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.connect"]>>
export type McpConnectOperation<E = never> = (input: Endpoint12_3Input) => Effect.Effect<Endpoint12_3Output, E>

type Endpoint12_4Request = Parameters<RawClient["server.mcp"]["mcp.disconnect"]>[0]
export type Endpoint12_4Input = {
  readonly server: Endpoint12_4Request["params"]["server"]
  readonly location?: Endpoint12_4Request["query"]["location"]
}
export type Endpoint12_4Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.disconnect"]>>
export type McpDisconnectOperation<E = never> = (input: Endpoint12_4Input) => Effect.Effect<Endpoint12_4Output, E>

type Endpoint12_5Request = Parameters<RawClient["server.mcp"]["mcp.resource.catalog"]>[0]
export type Endpoint12_5Input = { readonly location?: Endpoint12_5Request["query"]["location"] }
export type Endpoint12_5Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.resource.catalog"]>>
export type McpResourceCatalogOperation<E = never> = (input?: Endpoint12_5Input) => Effect.Effect<Endpoint12_5Output, E>

export interface McpApi<E = never> {
  readonly list: McpListOperation<E>
  readonly add: McpAddOperation<E>
  readonly remove: McpRemoveOperation<E>
  readonly connect: McpConnectOperation<E>
  readonly disconnect: McpDisconnectOperation<E>
  readonly resource: { readonly catalog: McpResourceCatalogOperation<E> }
}

type Endpoint13_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
export type Endpoint13_0Input = {
  readonly credentialID: Endpoint13_0Request["params"]["credentialID"]
  readonly location?: Endpoint13_0Request["query"]["location"]
  readonly label: Endpoint13_0Request["payload"]["label"]
}
export type Endpoint13_0Output = EffectValue<ReturnType<RawClient["server.credential"]["credential.update"]>>
export type CredentialUpdateOperation<E = never> = (input: Endpoint13_0Input) => Effect.Effect<Endpoint13_0Output, E>

type Endpoint13_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
export type Endpoint13_1Input = {
  readonly credentialID: Endpoint13_1Request["params"]["credentialID"]
  readonly location?: Endpoint13_1Request["query"]["location"]
}
export type Endpoint13_1Output = EffectValue<ReturnType<RawClient["server.credential"]["credential.remove"]>>
export type CredentialRemoveOperation<E = never> = (input: Endpoint13_1Input) => Effect.Effect<Endpoint13_1Output, E>

export interface CredentialApi<E = never> {
  readonly update: CredentialUpdateOperation<E>
  readonly remove: CredentialRemoveOperation<E>
}

export type Endpoint14_0Output = EffectValue<ReturnType<RawClient["server.project"]["project.list"]>>
export type ProjectListOperation<E = never> = () => Effect.Effect<Endpoint14_0Output, E>

type Endpoint14_1Request = Parameters<RawClient["server.project"]["project.current"]>[0]
export type Endpoint14_1Input = { readonly location?: Endpoint14_1Request["query"]["location"] }
export type Endpoint14_1Output = EffectValue<ReturnType<RawClient["server.project"]["project.current"]>>
export type ProjectCurrentOperation<E = never> = (input?: Endpoint14_1Input) => Effect.Effect<Endpoint14_1Output, E>

type Endpoint14_2Request = Parameters<RawClient["server.project"]["project.directories"]>[0]
export type Endpoint14_2Input = {
  readonly projectID: Endpoint14_2Request["params"]["projectID"]
  readonly location?: Endpoint14_2Request["query"]["location"]
}
export type Endpoint14_2Output = EffectValue<ReturnType<RawClient["server.project"]["project.directories"]>>
export type ProjectDirectoriesOperation<E = never> = (input: Endpoint14_2Input) => Effect.Effect<Endpoint14_2Output, E>

export interface ProjectApi<E = never> {
  readonly list: ProjectListOperation<E>
  readonly current: ProjectCurrentOperation<E>
  readonly directories: ProjectDirectoriesOperation<E>
}

type Endpoint15_0Request = Parameters<RawClient["server.form"]["form.request.list"]>[0]
export type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
export type Endpoint15_0Output = EffectValue<ReturnType<RawClient["server.form"]["form.request.list"]>>
export type FormRequestListOperation<E = never> = (input?: Endpoint15_0Input) => Effect.Effect<Endpoint15_0Output, E>

type Endpoint15_1Request = Parameters<RawClient["server.form"]["session.form.list"]>[0]
export type Endpoint15_1Input = { readonly sessionID: Endpoint15_1Request["params"]["sessionID"] }
export type Endpoint15_1Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.list"]>>["data"]
export type FormListOperation<E = never> = (input: Endpoint15_1Input) => Effect.Effect<Endpoint15_1Output, E>

type Endpoint15_2Request = Parameters<RawClient["server.form"]["session.form.create"]>[0]
export type Endpoint15_2Input = {
  readonly sessionID: Endpoint15_2Request["params"]["sessionID"]
  readonly id?: Endpoint15_2Request["payload"]["id"]
  readonly title: Endpoint15_2Request["payload"]["title"]
  readonly metadata?: Endpoint15_2Request["payload"]["metadata"]
  readonly fields: Endpoint15_2Request["payload"]["fields"]
}
export type Endpoint15_2Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.create"]>>["data"]
export type FormCreateOperation<E = never> = (input: Endpoint15_2Input) => Effect.Effect<Endpoint15_2Output, E>

type Endpoint15_3Request = Parameters<RawClient["server.form"]["session.form.get"]>[0]
export type Endpoint15_3Input = {
  readonly sessionID: Endpoint15_3Request["params"]["sessionID"]
  readonly formID: Endpoint15_3Request["params"]["formID"]
}
export type Endpoint15_3Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.get"]>>["data"]
export type FormGetOperation<E = never> = (input: Endpoint15_3Input) => Effect.Effect<Endpoint15_3Output, E>

type Endpoint15_4Request = Parameters<RawClient["server.form"]["session.form.state"]>[0]
export type Endpoint15_4Input = {
  readonly sessionID: Endpoint15_4Request["params"]["sessionID"]
  readonly formID: Endpoint15_4Request["params"]["formID"]
}
export type Endpoint15_4Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.state"]>>["data"]
export type FormStateOperation<E = never> = (input: Endpoint15_4Input) => Effect.Effect<Endpoint15_4Output, E>

type Endpoint15_5Request = Parameters<RawClient["server.form"]["session.form.reply"]>[0]
export type Endpoint15_5Input = {
  readonly sessionID: Endpoint15_5Request["params"]["sessionID"]
  readonly formID: Endpoint15_5Request["params"]["formID"]
  readonly answer: Endpoint15_5Request["payload"]["answer"]
}
export type Endpoint15_5Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.reply"]>>
export type FormReplyOperation<E = never> = (input: Endpoint15_5Input) => Effect.Effect<Endpoint15_5Output, E>

type Endpoint15_6Request = Parameters<RawClient["server.form"]["session.form.cancel"]>[0]
export type Endpoint15_6Input = {
  readonly sessionID: Endpoint15_6Request["params"]["sessionID"]
  readonly formID: Endpoint15_6Request["params"]["formID"]
}
export type Endpoint15_6Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.cancel"]>>
export type FormCancelOperation<E = never> = (input: Endpoint15_6Input) => Effect.Effect<Endpoint15_6Output, E>

export interface FormApi<E = never> {
  readonly request: { readonly list: FormRequestListOperation<E> }
  readonly list: FormListOperation<E>
  readonly create: FormCreateOperation<E>
  readonly get: FormGetOperation<E>
  readonly state: FormStateOperation<E>
  readonly reply: FormReplyOperation<E>
  readonly cancel: FormCancelOperation<E>
}

type Endpoint16_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
export type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
export type Endpoint16_0Output = EffectValue<ReturnType<RawClient["server.permission"]["permission.request.list"]>>
export type PermissionRequestListOperation<E = never> = (
  input?: Endpoint16_0Input,
) => Effect.Effect<Endpoint16_0Output, E>

type Endpoint16_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
export type Endpoint16_1Input = { readonly projectID?: Endpoint16_1Request["query"]["projectID"] }
export type Endpoint16_1Output = EffectValue<
  ReturnType<RawClient["server.permission"]["permission.saved.list"]>
>["data"]
export type PermissionSavedListOperation<E = never> = (
  input?: Endpoint16_1Input,
) => Effect.Effect<Endpoint16_1Output, E>

type Endpoint16_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
export type Endpoint16_2Input = { readonly id: Endpoint16_2Request["params"]["id"] }
export type Endpoint16_2Output = EffectValue<ReturnType<RawClient["server.permission"]["permission.saved.remove"]>>
export type PermissionSavedRemoveOperation<E = never> = (
  input: Endpoint16_2Input,
) => Effect.Effect<Endpoint16_2Output, E>

type Endpoint16_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
export type Endpoint16_3Input = {
  readonly sessionID: Endpoint16_3Request["params"]["sessionID"]
  readonly id?: Endpoint16_3Request["payload"]["id"]
  readonly action: Endpoint16_3Request["payload"]["action"]
  readonly resources: Endpoint16_3Request["payload"]["resources"]
  readonly save?: Endpoint16_3Request["payload"]["save"]
  readonly metadata?: Endpoint16_3Request["payload"]["metadata"]
  readonly source?: Endpoint16_3Request["payload"]["source"]
  readonly agent?: Endpoint16_3Request["payload"]["agent"]
}
export type Endpoint16_3Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.create"]>
>["data"]
export type PermissionCreateOperation<E = never> = (input: Endpoint16_3Input) => Effect.Effect<Endpoint16_3Output, E>

type Endpoint16_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
export type Endpoint16_4Input = { readonly sessionID: Endpoint16_4Request["params"]["sessionID"] }
export type Endpoint16_4Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.list"]>
>["data"]
export type PermissionListOperation<E = never> = (input: Endpoint16_4Input) => Effect.Effect<Endpoint16_4Output, E>

type Endpoint16_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
export type Endpoint16_5Input = {
  readonly sessionID: Endpoint16_5Request["params"]["sessionID"]
  readonly requestID: Endpoint16_5Request["params"]["requestID"]
}
export type Endpoint16_5Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.get"]>
>["data"]
export type PermissionGetOperation<E = never> = (input: Endpoint16_5Input) => Effect.Effect<Endpoint16_5Output, E>

type Endpoint16_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
export type Endpoint16_6Input = {
  readonly sessionID: Endpoint16_6Request["params"]["sessionID"]
  readonly requestID: Endpoint16_6Request["params"]["requestID"]
  readonly reply: Endpoint16_6Request["payload"]["reply"]
  readonly message?: Endpoint16_6Request["payload"]["message"]
}
export type Endpoint16_6Output = EffectValue<ReturnType<RawClient["server.permission"]["session.permission.reply"]>>
export type PermissionReplyOperation<E = never> = (input: Endpoint16_6Input) => Effect.Effect<Endpoint16_6Output, E>

export interface PermissionApi<E = never> {
  readonly request: { readonly list: PermissionRequestListOperation<E> }
  readonly saved: { readonly list: PermissionSavedListOperation<E>; readonly remove: PermissionSavedRemoveOperation<E> }
  readonly create: PermissionCreateOperation<E>
  readonly list: PermissionListOperation<E>
  readonly get: PermissionGetOperation<E>
  readonly reply: PermissionReplyOperation<E>
}

type Endpoint17_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
export type Endpoint17_0Input = {
  readonly location?: Endpoint17_0Request["query"]["location"]
  readonly path?: Endpoint17_0Request["query"]["path"]
}
export type Endpoint17_0Output = EffectValue<ReturnType<RawClient["server.fs"]["fs.list"]>>
export type FileListOperation<E = never> = (input?: Endpoint17_0Input) => Effect.Effect<Endpoint17_0Output, E>

type Endpoint17_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
export type Endpoint17_1Input = {
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly query: Endpoint17_1Request["query"]["query"]
  readonly type?: Endpoint17_1Request["query"]["type"]
  readonly limit?: Endpoint17_1Request["query"]["limit"]
}
export type Endpoint17_1Output = EffectValue<ReturnType<RawClient["server.fs"]["fs.find"]>>
export type FileFindOperation<E = never> = (input: Endpoint17_1Input) => Effect.Effect<Endpoint17_1Output, E>

export interface FileApi<E = never> {
  readonly list: FileListOperation<E>
  readonly find: FileFindOperation<E>
}

type Endpoint18_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
export type Endpoint18_0Input = { readonly location?: Endpoint18_0Request["query"]["location"] }
export type Endpoint18_0Output = EffectValue<ReturnType<RawClient["server.command"]["command.list"]>>
export type CommandListOperation<E = never> = (input?: Endpoint18_0Input) => Effect.Effect<Endpoint18_0Output, E>

export interface CommandApi<E = never> {
  readonly list: CommandListOperation<E>
}

type Endpoint19_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
export type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
export type Endpoint19_0Output = EffectValue<ReturnType<RawClient["server.skill"]["skill.list"]>>
export type SkillListOperation<E = never> = (input?: Endpoint19_0Input) => Effect.Effect<Endpoint19_0Output, E>

export interface SkillApi<E = never> {
  readonly list: SkillListOperation<E>
}

export type Endpoint20_0Output = StreamValue<EffectValue<ReturnType<RawClient["server.event"]["event.subscribe"]>>>
export type EventSubscribeOperation<E = never> = () => Stream.Stream<Endpoint20_0Output, E>

export interface EventApi<E = never> {
  readonly subscribe: EventSubscribeOperation<E>
}

type Endpoint21_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
export type Endpoint21_0Input = { readonly location?: Endpoint21_0Request["query"]["location"] }
export type Endpoint21_0Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.list"]>>
export type PtyListOperation<E = never> = (input?: Endpoint21_0Input) => Effect.Effect<Endpoint21_0Output, E>

type Endpoint21_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
export type Endpoint21_1Input = {
  readonly location?: Endpoint21_1Request["query"]["location"]
  readonly command?: Endpoint21_1Request["payload"]["command"]
  readonly args?: Endpoint21_1Request["payload"]["args"]
  readonly cwd?: Endpoint21_1Request["payload"]["cwd"]
  readonly title?: Endpoint21_1Request["payload"]["title"]
  readonly env?: Endpoint21_1Request["payload"]["env"]
}
export type Endpoint21_1Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.create"]>>
export type PtyCreateOperation<E = never> = (input?: Endpoint21_1Input) => Effect.Effect<Endpoint21_1Output, E>

type Endpoint21_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
export type Endpoint21_2Input = {
  readonly ptyID: Endpoint21_2Request["params"]["ptyID"]
  readonly location?: Endpoint21_2Request["query"]["location"]
}
export type Endpoint21_2Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.get"]>>
export type PtyGetOperation<E = never> = (input: Endpoint21_2Input) => Effect.Effect<Endpoint21_2Output, E>

type Endpoint21_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
export type Endpoint21_3Input = {
  readonly ptyID: Endpoint21_3Request["params"]["ptyID"]
  readonly location?: Endpoint21_3Request["query"]["location"]
  readonly title?: Endpoint21_3Request["payload"]["title"]
  readonly size?: Endpoint21_3Request["payload"]["size"]
}
export type Endpoint21_3Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.update"]>>
export type PtyUpdateOperation<E = never> = (input: Endpoint21_3Input) => Effect.Effect<Endpoint21_3Output, E>

type Endpoint21_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
export type Endpoint21_4Input = {
  readonly ptyID: Endpoint21_4Request["params"]["ptyID"]
  readonly location?: Endpoint21_4Request["query"]["location"]
}
export type Endpoint21_4Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.remove"]>>
export type PtyRemoveOperation<E = never> = (input: Endpoint21_4Input) => Effect.Effect<Endpoint21_4Output, E>

export interface PtyApi<E = never> {
  readonly list: PtyListOperation<E>
  readonly create: PtyCreateOperation<E>
  readonly get: PtyGetOperation<E>
  readonly update: PtyUpdateOperation<E>
  readonly remove: PtyRemoveOperation<E>
}

type Endpoint22_0Request = Parameters<RawClient["server.shell"]["shell.list"]>[0]
export type Endpoint22_0Input = { readonly location?: Endpoint22_0Request["query"]["location"] }
export type Endpoint22_0Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.list"]>>
export type ShellListOperation<E = never> = (input?: Endpoint22_0Input) => Effect.Effect<Endpoint22_0Output, E>

type Endpoint22_1Request = Parameters<RawClient["server.shell"]["shell.create"]>[0]
export type Endpoint22_1Input = {
  readonly location?: Endpoint22_1Request["query"]["location"]
  readonly command: Endpoint22_1Request["payload"]["command"]
  readonly cwd?: Endpoint22_1Request["payload"]["cwd"]
  readonly timeout: Endpoint22_1Request["payload"]["timeout"]
  readonly metadata?: Endpoint22_1Request["payload"]["metadata"]
}
export type Endpoint22_1Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.create"]>>
export type ShellCreateOperation<E = never> = (input: Endpoint22_1Input) => Effect.Effect<Endpoint22_1Output, E>

type Endpoint22_2Request = Parameters<RawClient["server.shell"]["shell.get"]>[0]
export type Endpoint22_2Input = {
  readonly id: Endpoint22_2Request["params"]["id"]
  readonly location?: Endpoint22_2Request["query"]["location"]
}
export type Endpoint22_2Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.get"]>>
export type ShellGetOperation<E = never> = (input: Endpoint22_2Input) => Effect.Effect<Endpoint22_2Output, E>

type Endpoint22_3Request = Parameters<RawClient["server.shell"]["shell.timeout"]>[0]
export type Endpoint22_3Input = {
  readonly id: Endpoint22_3Request["params"]["id"]
  readonly location?: Endpoint22_3Request["query"]["location"]
  readonly timeout: Endpoint22_3Request["payload"]["timeout"]
}
export type Endpoint22_3Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.timeout"]>>
export type ShellTimeoutOperation<E = never> = (input: Endpoint22_3Input) => Effect.Effect<Endpoint22_3Output, E>

type Endpoint22_4Request = Parameters<RawClient["server.shell"]["shell.output"]>[0]
export type Endpoint22_4Input = {
  readonly id: Endpoint22_4Request["params"]["id"]
  readonly location?: Endpoint22_4Request["query"]["location"]
  readonly cursor?: Endpoint22_4Request["query"]["cursor"]
  readonly limit?: Endpoint22_4Request["query"]["limit"]
}
export type Endpoint22_4Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.output"]>>
export type ShellOutputOperation<E = never> = (input: Endpoint22_4Input) => Effect.Effect<Endpoint22_4Output, E>

type Endpoint22_5Request = Parameters<RawClient["server.shell"]["shell.remove"]>[0]
export type Endpoint22_5Input = {
  readonly id: Endpoint22_5Request["params"]["id"]
  readonly location?: Endpoint22_5Request["query"]["location"]
}
export type Endpoint22_5Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.remove"]>>
export type ShellRemoveOperation<E = never> = (input: Endpoint22_5Input) => Effect.Effect<Endpoint22_5Output, E>

export interface ShellApi<E = never> {
  readonly list: ShellListOperation<E>
  readonly create: ShellCreateOperation<E>
  readonly get: ShellGetOperation<E>
  readonly timeout: ShellTimeoutOperation<E>
  readonly output: ShellOutputOperation<E>
  readonly remove: ShellRemoveOperation<E>
}

type Endpoint23_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
export type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
export type Endpoint23_0Output = EffectValue<ReturnType<RawClient["server.question"]["question.request.list"]>>
export type QuestionRequestListOperation<E = never> = (
  input?: Endpoint23_0Input,
) => Effect.Effect<Endpoint23_0Output, E>

type Endpoint23_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
export type Endpoint23_1Input = { readonly sessionID: Endpoint23_1Request["params"]["sessionID"] }
export type Endpoint23_1Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.list"]>>["data"]
export type QuestionListOperation<E = never> = (input: Endpoint23_1Input) => Effect.Effect<Endpoint23_1Output, E>

type Endpoint23_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
export type Endpoint23_2Input = {
  readonly sessionID: Endpoint23_2Request["params"]["sessionID"]
  readonly requestID: Endpoint23_2Request["params"]["requestID"]
  readonly answers: Endpoint23_2Request["payload"]["answers"]
}
export type Endpoint23_2Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.reply"]>>
export type QuestionReplyOperation<E = never> = (input: Endpoint23_2Input) => Effect.Effect<Endpoint23_2Output, E>

type Endpoint23_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
export type Endpoint23_3Input = {
  readonly sessionID: Endpoint23_3Request["params"]["sessionID"]
  readonly requestID: Endpoint23_3Request["params"]["requestID"]
}
export type Endpoint23_3Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.reject"]>>
export type QuestionRejectOperation<E = never> = (input: Endpoint23_3Input) => Effect.Effect<Endpoint23_3Output, E>

export interface QuestionApi<E = never> {
  readonly request: { readonly list: QuestionRequestListOperation<E> }
  readonly list: QuestionListOperation<E>
  readonly reply: QuestionReplyOperation<E>
  readonly reject: QuestionRejectOperation<E>
}

type Endpoint24_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
export type Endpoint24_0Input = { readonly location?: Endpoint24_0Request["query"]["location"] }
export type Endpoint24_0Output = EffectValue<ReturnType<RawClient["server.reference"]["reference.list"]>>
export type ReferenceListOperation<E = never> = (input?: Endpoint24_0Input) => Effect.Effect<Endpoint24_0Output, E>

export interface ReferenceApi<E = never> {
  readonly list: ReferenceListOperation<E>
}

type Endpoint25_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
export type Endpoint25_0Input = {
  readonly projectID: Endpoint25_0Request["params"]["projectID"]
  readonly location?: Endpoint25_0Request["query"]["location"]
  readonly strategy: Endpoint25_0Request["payload"]["strategy"]
  readonly directory: Endpoint25_0Request["payload"]["directory"]
  readonly name?: Endpoint25_0Request["payload"]["name"]
}
export type Endpoint25_0Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.create"]>>
export type ProjectCopyCreateOperation<E = never> = (input: Endpoint25_0Input) => Effect.Effect<Endpoint25_0Output, E>

type Endpoint25_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
export type Endpoint25_1Input = {
  readonly projectID: Endpoint25_1Request["params"]["projectID"]
  readonly location?: Endpoint25_1Request["query"]["location"]
  readonly directory: Endpoint25_1Request["payload"]["directory"]
  readonly force: Endpoint25_1Request["payload"]["force"]
}
export type Endpoint25_1Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.remove"]>>
export type ProjectCopyRemoveOperation<E = never> = (input: Endpoint25_1Input) => Effect.Effect<Endpoint25_1Output, E>

type Endpoint25_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
export type Endpoint25_2Input = {
  readonly projectID: Endpoint25_2Request["params"]["projectID"]
  readonly location?: Endpoint25_2Request["query"]["location"]
}
export type Endpoint25_2Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.refresh"]>>
export type ProjectCopyRefreshOperation<E = never> = (input: Endpoint25_2Input) => Effect.Effect<Endpoint25_2Output, E>

export interface ProjectCopyApi<E = never> {
  readonly create: ProjectCopyCreateOperation<E>
  readonly remove: ProjectCopyRemoveOperation<E>
  readonly refresh: ProjectCopyRefreshOperation<E>
}

type Endpoint26_0Request = Parameters<RawClient["server.vcs"]["vcs.status"]>[0]
export type Endpoint26_0Input = { readonly location?: Endpoint26_0Request["query"]["location"] }
export type Endpoint26_0Output = EffectValue<ReturnType<RawClient["server.vcs"]["vcs.status"]>>
export type VcsStatusOperation<E = never> = (input?: Endpoint26_0Input) => Effect.Effect<Endpoint26_0Output, E>

type Endpoint26_1Request = Parameters<RawClient["server.vcs"]["vcs.diff"]>[0]
export type Endpoint26_1Input = {
  readonly location?: Endpoint26_1Request["query"]["location"]
  readonly mode: Endpoint26_1Request["query"]["mode"]
  readonly context?: Endpoint26_1Request["query"]["context"]
}
export type Endpoint26_1Output = EffectValue<ReturnType<RawClient["server.vcs"]["vcs.diff"]>>
export type VcsDiffOperation<E = never> = (input: Endpoint26_1Input) => Effect.Effect<Endpoint26_1Output, E>

export interface VcsApi<E = never> {
  readonly status: VcsStatusOperation<E>
  readonly diff: VcsDiffOperation<E>
}

type Endpoint27_0Request = Parameters<RawClient["server.projectArtifact"]["artifact.list"]>[0]
export type Endpoint27_0Input = {
  readonly location?: Endpoint27_0Request["query"]["location"]
  readonly scope: Endpoint27_0Request["query"]["scope"]
  readonly kind?: Endpoint27_0Request["query"]["kind"]
  readonly stage?: Endpoint27_0Request["query"]["stage"]
}
export type Endpoint27_0Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.list"]>>["data"]
export type ProjectArtifactArtifactListOperation<E = never> = (
  input: Endpoint27_0Input,
) => Effect.Effect<Endpoint27_0Output, E>

type Endpoint27_1Request = Parameters<RawClient["server.projectArtifact"]["artifact.get"]>[0]
export type Endpoint27_1Input = {
  readonly scope: Endpoint27_1Request["params"]["scope"]
  readonly kind: Endpoint27_1Request["params"]["kind"]
  readonly id: Endpoint27_1Request["params"]["id"]
  readonly location?: Endpoint27_1Request["query"]["location"]
}
export type Endpoint27_1Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.get"]>>["data"]
export type ProjectArtifactArtifactGetOperation<E = never> = (
  input: Endpoint27_1Input,
) => Effect.Effect<Endpoint27_1Output, E>

type Endpoint27_2Request = Parameters<RawClient["server.projectArtifact"]["artifact.create"]>[0]
export type Endpoint27_2Input = {
  readonly location?: Endpoint27_2Request["query"]["location"]
  readonly scope: Endpoint27_2Request["payload"]["scope"]
  readonly id: Endpoint27_2Request["payload"]["id"]
  readonly definition: Endpoint27_2Request["payload"]["definition"]
}
export type Endpoint27_2Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.create"]>>["data"]
export type ProjectArtifactArtifactCreateOperation<E = never> = (
  input: Endpoint27_2Input,
) => Effect.Effect<Endpoint27_2Output, E>

type Endpoint27_3Request = Parameters<RawClient["server.projectArtifact"]["artifact.update"]>[0]
export type Endpoint27_3Input = {
  readonly scope: Endpoint27_3Request["params"]["scope"]
  readonly kind: Endpoint27_3Request["params"]["kind"]
  readonly id: Endpoint27_3Request["params"]["id"]
  readonly location?: Endpoint27_3Request["query"]["location"]
  readonly definition: Endpoint27_3Request["payload"]["definition"]
  readonly expectedRevision: Endpoint27_3Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_3Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_3Request["payload"]["expectedDigest"]
}
export type Endpoint27_3Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.update"]>>["data"]
export type ProjectArtifactArtifactUpdateOperation<E = never> = (
  input: Endpoint27_3Input,
) => Effect.Effect<Endpoint27_3Output, E>

type Endpoint27_4Request = Parameters<RawClient["server.projectArtifact"]["artifact.confirmGlobal"]>[0]
export type Endpoint27_4Input = {
  readonly location?: Endpoint27_4Request["query"]["location"]
  readonly token: Endpoint27_4Request["payload"]["token"]
}
export type Endpoint27_4Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.confirmGlobal"]>
>["data"]
export type ProjectArtifactArtifactGlobalConfirmOperation<E = never> = (
  input: Endpoint27_4Input,
) => Effect.Effect<Endpoint27_4Output, E>

type Endpoint27_5Request = Parameters<RawClient["server.projectArtifact"]["artifact.disable"]>[0]
export type Endpoint27_5Input = {
  readonly scope: Endpoint27_5Request["params"]["scope"]
  readonly kind: Endpoint27_5Request["params"]["kind"]
  readonly id: Endpoint27_5Request["params"]["id"]
  readonly location?: Endpoint27_5Request["query"]["location"]
  readonly expectedRevision: Endpoint27_5Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_5Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_5Request["payload"]["expectedDigest"]
}
export type Endpoint27_5Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.disable"]>>
export type ProjectArtifactArtifactDisableOperation<E = never> = (
  input: Endpoint27_5Input,
) => Effect.Effect<Endpoint27_5Output, E>

type Endpoint27_6Request = Parameters<RawClient["server.projectArtifact"]["artifact.enable"]>[0]
export type Endpoint27_6Input = {
  readonly scope: Endpoint27_6Request["params"]["scope"]
  readonly kind: Endpoint27_6Request["params"]["kind"]
  readonly id: Endpoint27_6Request["params"]["id"]
  readonly location?: Endpoint27_6Request["query"]["location"]
  readonly expectedRevision: Endpoint27_6Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_6Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_6Request["payload"]["expectedDigest"]
}
export type Endpoint27_6Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.enable"]>>
export type ProjectArtifactArtifactEnableOperation<E = never> = (
  input: Endpoint27_6Input,
) => Effect.Effect<Endpoint27_6Output, E>

type Endpoint27_7Request = Parameters<RawClient["server.projectArtifact"]["artifact.remove"]>[0]
export type Endpoint27_7Input = {
  readonly scope: Endpoint27_7Request["params"]["scope"]
  readonly kind: Endpoint27_7Request["params"]["kind"]
  readonly id: Endpoint27_7Request["params"]["id"]
  readonly location?: Endpoint27_7Request["query"]["location"]
  readonly expectedRevision: Endpoint27_7Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_7Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_7Request["payload"]["expectedDigest"]
}
export type Endpoint27_7Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.remove"]>>["data"]
export type ProjectArtifactArtifactRemoveOperation<E = never> = (
  input: Endpoint27_7Input,
) => Effect.Effect<Endpoint27_7Output, E>

type Endpoint27_8Request = Parameters<RawClient["server.projectArtifact"]["artifact.restore"]>[0]
export type Endpoint27_8Input = {
  readonly deletionID: Endpoint27_8Request["params"]["deletionID"]
  readonly location?: Endpoint27_8Request["query"]["location"]
}
export type Endpoint27_8Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.restore"]>>
export type ProjectArtifactArtifactRestoreOperation<E = never> = (
  input: Endpoint27_8Input,
) => Effect.Effect<Endpoint27_8Output, E>

type Endpoint27_9Request = Parameters<RawClient["server.projectArtifact"]["artifact.revert"]>[0]
export type Endpoint27_9Input = {
  readonly scope: Endpoint27_9Request["params"]["scope"]
  readonly kind: Endpoint27_9Request["params"]["kind"]
  readonly id: Endpoint27_9Request["params"]["id"]
  readonly location?: Endpoint27_9Request["query"]["location"]
  readonly expectedRevision: Endpoint27_9Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_9Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_9Request["payload"]["expectedDigest"]
  readonly targetVersionID: Endpoint27_9Request["payload"]["targetVersionID"]
}
export type Endpoint27_9Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.revert"]>>
export type ProjectArtifactArtifactRevertOperation<E = never> = (
  input: Endpoint27_9Input,
) => Effect.Effect<Endpoint27_9Output, E>

type Endpoint27_10Request = Parameters<RawClient["server.projectArtifact"]["artifact.metrics"]>[0]
export type Endpoint27_10Input = {
  readonly scope: Endpoint27_10Request["params"]["scope"]
  readonly kind: Endpoint27_10Request["params"]["kind"]
  readonly id: Endpoint27_10Request["params"]["id"]
  readonly location?: Endpoint27_10Request["query"]["location"]
}
export type Endpoint27_10Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.metrics"]>
>["data"]
export type ProjectArtifactArtifactMetricsOperation<E = never> = (
  input: Endpoint27_10Input,
) => Effect.Effect<Endpoint27_10Output, E>

type Endpoint27_11Request = Parameters<RawClient["server.projectArtifact"]["artifact.promotion.preview"]>[0]
export type Endpoint27_11Input = {
  readonly kind: Endpoint27_11Request["params"]["kind"]
  readonly id: Endpoint27_11Request["params"]["id"]
  readonly location?: Endpoint27_11Request["query"]["location"]
  readonly expectedRevision: Endpoint27_11Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_11Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_11Request["payload"]["expectedDigest"]
}
export type Endpoint27_11Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.promotion.preview"]>
>["data"]
export type ProjectArtifactArtifactPromotionPreviewOperation<E = never> = (
  input: Endpoint27_11Input,
) => Effect.Effect<Endpoint27_11Output, E>

type Endpoint27_12Request = Parameters<RawClient["server.projectArtifact"]["artifact.promotion.confirm"]>[0]
export type Endpoint27_12Input = {
  readonly kind: Endpoint27_12Request["params"]["kind"]
  readonly id: Endpoint27_12Request["params"]["id"]
  readonly token: Endpoint27_12Request["params"]["token"]
  readonly location?: Endpoint27_12Request["query"]["location"]
}
export type Endpoint27_12Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.promotion.confirm"]>
>["data"]
export type ProjectArtifactArtifactPromotionConfirmOperation<E = never> = (
  input: Endpoint27_12Input,
) => Effect.Effect<Endpoint27_12Output, E>

type Endpoint27_13Request = Parameters<RawClient["server.projectArtifact"]["artifact.fork.preview"]>[0]
export type Endpoint27_13Input = {
  readonly kind: Endpoint27_13Request["params"]["kind"]
  readonly id: Endpoint27_13Request["params"]["id"]
  readonly location?: Endpoint27_13Request["query"]["location"]
  readonly expectedRevision: Endpoint27_13Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_13Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_13Request["payload"]["expectedDigest"]
}
export type Endpoint27_13Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.fork.preview"]>
>["data"]
export type ProjectArtifactArtifactForkPreviewOperation<E = never> = (
  input: Endpoint27_13Input,
) => Effect.Effect<Endpoint27_13Output, E>

type Endpoint27_14Request = Parameters<RawClient["server.projectArtifact"]["artifact.fork.confirm"]>[0]
export type Endpoint27_14Input = {
  readonly kind: Endpoint27_14Request["params"]["kind"]
  readonly id: Endpoint27_14Request["params"]["id"]
  readonly token: Endpoint27_14Request["params"]["token"]
  readonly location?: Endpoint27_14Request["query"]["location"]
}
export type Endpoint27_14Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.fork.confirm"]>
>["data"]
export type ProjectArtifactArtifactForkConfirmOperation<E = never> = (
  input: Endpoint27_14Input,
) => Effect.Effect<Endpoint27_14Output, E>

type Endpoint27_15Request = Parameters<RawClient["server.projectArtifact"]["artifact.shadow.preview"]>[0]
export type Endpoint27_15Input = {
  readonly kind: Endpoint27_15Request["params"]["kind"]
  readonly id: Endpoint27_15Request["params"]["id"]
  readonly location?: Endpoint27_15Request["query"]["location"]
  readonly expectedRevision: Endpoint27_15Request["payload"]["expectedRevision"]
  readonly expectedVersionID: Endpoint27_15Request["payload"]["expectedVersionID"]
  readonly expectedDigest: Endpoint27_15Request["payload"]["expectedDigest"]
}
export type Endpoint27_15Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.shadow.preview"]>
>["data"]
export type ProjectArtifactArtifactShadowPreviewOperation<E = never> = (
  input: Endpoint27_15Input,
) => Effect.Effect<Endpoint27_15Output, E>

type Endpoint27_16Request = Parameters<RawClient["server.projectArtifact"]["artifact.shadow.confirm"]>[0]
export type Endpoint27_16Input = {
  readonly kind: Endpoint27_16Request["params"]["kind"]
  readonly id: Endpoint27_16Request["params"]["id"]
  readonly token: Endpoint27_16Request["params"]["token"]
  readonly location?: Endpoint27_16Request["query"]["location"]
}
export type Endpoint27_16Output = EffectValue<
  ReturnType<RawClient["server.projectArtifact"]["artifact.shadow.confirm"]>
>
export type ProjectArtifactArtifactShadowConfirmOperation<E = never> = (
  input: Endpoint27_16Input,
) => Effect.Effect<Endpoint27_16Output, E>

type Endpoint27_17Request = Parameters<RawClient["server.projectArtifact"]["artifact.purge"]>[0]
export type Endpoint27_17Input = { readonly location?: Endpoint27_17Request["query"]["location"] }
export type Endpoint27_17Output = EffectValue<ReturnType<RawClient["server.projectArtifact"]["artifact.purge"]>>["data"]
export type ProjectArtifactArtifactPurgeOperation<E = never> = (
  input?: Endpoint27_17Input,
) => Effect.Effect<Endpoint27_17Output, E>

export interface ProjectArtifactApi<E = never> {
  readonly artifact: {
    readonly list: ProjectArtifactArtifactListOperation<E>
    readonly get: ProjectArtifactArtifactGetOperation<E>
    readonly create: ProjectArtifactArtifactCreateOperation<E>
    readonly update: ProjectArtifactArtifactUpdateOperation<E>
    readonly global: { readonly confirm: ProjectArtifactArtifactGlobalConfirmOperation<E> }
    readonly disable: ProjectArtifactArtifactDisableOperation<E>
    readonly enable: ProjectArtifactArtifactEnableOperation<E>
    readonly remove: ProjectArtifactArtifactRemoveOperation<E>
    readonly restore: ProjectArtifactArtifactRestoreOperation<E>
    readonly revert: ProjectArtifactArtifactRevertOperation<E>
    readonly metrics: ProjectArtifactArtifactMetricsOperation<E>
    readonly promotion: {
      readonly preview: ProjectArtifactArtifactPromotionPreviewOperation<E>
      readonly confirm: ProjectArtifactArtifactPromotionConfirmOperation<E>
    }
    readonly fork: {
      readonly preview: ProjectArtifactArtifactForkPreviewOperation<E>
      readonly confirm: ProjectArtifactArtifactForkConfirmOperation<E>
    }
    readonly shadow: {
      readonly preview: ProjectArtifactArtifactShadowPreviewOperation<E>
      readonly confirm: ProjectArtifactArtifactShadowConfirmOperation<E>
    }
    readonly purge: ProjectArtifactArtifactPurgeOperation<E>
  }
}

export type Endpoint28_0Output = EffectValue<ReturnType<RawClient["server.debug"]["debug.location"]>>
export type DebugLocationListOperation<E = never> = () => Effect.Effect<Endpoint28_0Output, E>

type Endpoint28_1Request = Parameters<RawClient["server.debug"]["debug.location.evict"]>[0]
export type Endpoint28_1Input = { readonly location?: Endpoint28_1Request["query"]["location"] }
export type Endpoint28_1Output = EffectValue<ReturnType<RawClient["server.debug"]["debug.location.evict"]>>
export type DebugLocationEvictOperation<E = never> = (input?: Endpoint28_1Input) => Effect.Effect<Endpoint28_1Output, E>

export interface DebugApi<E = never> {
  readonly location: { readonly list: DebugLocationListOperation<E>; readonly evict: DebugLocationEvictOperation<E> }
}

export interface AppApi<E = never> {
  readonly health: HealthApi<E>
  readonly server: ServerApi<E>
  readonly location: LocationApi<E>
  readonly agent: AgentApi<E>
  readonly plugin: PluginApi<E>
  readonly session: SessionApi<E>
  readonly guardrail: GuardrailApi<E>
  readonly message: MessageApi<E>
  readonly model: ModelApi<E>
  readonly generate: GenerateApi<E>
  readonly provider: ProviderApi<E>
  readonly integration: IntegrationApi<E>
  readonly mcp: McpApi<E>
  readonly credential: CredentialApi<E>
  readonly project: ProjectApi<E>
  readonly form: FormApi<E>
  readonly permission: PermissionApi<E>
  readonly file: FileApi<E>
  readonly command: CommandApi<E>
  readonly skill: SkillApi<E>
  readonly event: EventApi<E>
  readonly pty: PtyApi<E>
  readonly shell: ShellApi<E>
  readonly question: QuestionApi<E>
  readonly reference: ReferenceApi<E>
  readonly projectCopy: ProjectCopyApi<E>
  readonly vcs: VcsApi<E>
  readonly projectArtifact: ProjectArtifactApi<E>
  readonly debug: DebugApi<E>
}
