#!/usr/bin/env python3
"""Render the two human-readable task views. Python 3.10+, no dependencies."""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATUS_LABELS = {"todo":"Not started", "in_progress":"In progress", "blocked":"Blocked", "in_review":"In review", "done":"Done", "deferred":"Deferred"}

def render(data: dict) -> dict[str, str]:
    tasks = data["tasks"]
    by_id = {t["id"]: t for t in tasks}
    counts = {s: sum(t["status"] == s for t in tasks) for s in STATUS_LABELS}
    ready = [t for t in tasks if t["status"] == "todo" and all(by_id[d]["status"] == "done" for d in t["depends_on"])]
    lines = ["# Implementation tracking", "", "<!-- Generated by tools/render_tracking.py. Edit tracking/tasks.json, not this file. -->", "",
             f"Project: **{data['project']}** · Data updated: **{data['updated_on']}**", "",
             f"**{counts['done']}/{len(tasks)} implementation tasks done.** Pack creation is not application progress.", "",
             "| State | Count |", "|---|---:|"]
    lines += [f"| {label} | {counts[status]} |" for status, label in STATUS_LABELS.items()]
    lines += ["", "## Milestones", "", "| Milestone | Done / total | Gate task | Gate status |", "|---|---:|---|---|"]
    for m in data["milestones"]:
        owned = [t for t in tasks if t["milestone"] == m["id"]]
        gate = by_id[m["gate_task"]]
        lines.append(f"| {m['id']} — {m['title']} | {sum(t['status']=='done' for t in owned)} / {len(owned)} | {gate['id']} | {STATUS_LABELS[gate['status']]} |")
    lines += ["", "## Dependency-ready tasks", ""]
    lines += [f"- **{t['id']}** — {t['title']}" for t in ready] or ["No unstarted task is currently dependency-ready. Inspect in-progress/review/blocked tasks."]
    lines += ["", "## Rules", "", "Canonical state: [tracking/tasks.json](tracking/tasks.json). Full acceptance/dependencies: [TODO.md](TODO.md). Current next-session context: [tracking/HANDOFF.md](tracking/HANDOFF.md).", "",
              "Use actual evidence before marking done. Satisfy dependencies. M2/M4 require recorded user visual review of real Godot captures. Update the session log and handoff, then regenerate these views. Do not use the number of files created as progress toward fidelity or live integration.", ""]
    todo = ["# Task checklist", "", "<!-- Generated by tools/render_tracking.py. Edit tracking/tasks.json, not this file. -->", "",
            "All paths under planned outputs are future implementation outputs, not assertions that files exist. Sizes S/M/L are relative work sizes, not time estimates. Only a checked box means status `done`; read the explicit status for blocked/in-review work.", ""]
    for m in data["milestones"]:
        todo += [f"## {m['id']} — {m['title']}", ""]
        for t in [t for t in tasks if t["milestone"] == m["id"]]:
            todo += [f"- [{'x' if t['status']=='done' else ' '}] **{t['id']} — {t['title']}**", f"  - Status: `{t['status']}` · Size: {t['size']} · Owner: {t['owner'] or 'unassigned'}.",
                     f"  - Depends on: {', '.join(t['depends_on']) or 'none'}.", f"  - Requirements: {', '.join(t['requirement_ids'])}. Tests: {', '.join(t['test_ids'])}."]
            todo += [f"  - Acceptance: {a}" for a in t["acceptance"]]
            todo += [f"  - Planned outputs: {'; '.join(t['planned_outputs'])}."]
            if t["requires_user_review"]:
                todo += ["  - **User visual acceptance required; implementing agent cannot self-approve.**"]
            todo += [f"  - Evidence: {', '.join(t['evidence']) or 'none; not yet verified'}.", ""]
    todo += ["Update [tracking/tasks.json](tracking/tasks.json), then run `python3 tools/render_tracking.py`. See [CHECKLIST.md](CHECKLIST.md) and [MILESTONES.md](MILESTONES.md) for gate rules.", ""]
    return {"TRACKING.md": "\n".join(lines), "TODO.md": "\n".join(todo)}

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale; do not write.")
    args = parser.parse_args()
    try:
        data = json.loads((ROOT / "tracking/tasks.json").read_text(encoding="utf8"))
        views = render(data)
        stale = []
        for name, content in views.items():
            path = ROOT / name
            if args.check:
                if not path.exists() or path.read_text(encoding="utf8") != content:
                    stale.append(name)
            else:
                path.write_text(content, encoding="utf8")
        if stale:
            print("Stale generated views: " + ", ".join(stale))
            return 1
        print("Tracking views are current." if args.check else "Updated TRACKING.md and TODO.md.")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Tracking render failed: {exc}")
        return 1

if __name__ == "__main__":
    raise SystemExit(main())
