export declare function isProjectDiscoveryDisabled(): boolean;
export declare function ycodingProjectConfigDirs(workspaceRoot: string): string[];
export declare function ycodingGlobalConfigDirs(): string[];
export declare function ycodingConfigFileNames(): string[];
export declare function setHostCacheDirOverride(dir: string | undefined): void;
export declare function ycodingGlobalConfigDir(): string;
export declare function cursorCacheDir(): string;
export declare function hostPlansDir(_workspaceRoot?: string): string;
export declare function slugifyWorkspacePath(workspaceRoot: string): string;
export declare function cursorProjectDir(workspaceRoot: string): string;
export declare function ensureCursorProjectDir(workspaceRoot: string): string;
export declare function resolveHomeRelative(p: string): string;
